name: 'Node.js Build and Test'
description: 'Setup Node.js, install dependencies, build TypeScript, and run tests'
inputs:
  node_version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  cache:
    description: 'Enable npm cache'
    required: false
    default: 'npm'
runs:
  using: "composite"
  steps:
    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: ${{ inputs.cache }}

    - name: 📥 Install dependencies
      shell: bash
      run: |
        echo "📥 Installing dependencies..."
        npm ci
        echo "✅ Dependencies installed successfully"

    - name: 🔨 Build TypeScript
      shell: bash
      run: |
        echo "🔨 Building TypeScript..."
        npm run build
        echo "✅ Build completed successfully"

    - name: 🧪 Run tests
      shell: bash
      run: |
        if npm run test --dry-run 2>/dev/null; then
          echo "🧪 Running tests..."
          npm test
          echo "✅ Tests completed successfully"
        else
          echo "⚠️ No tests found, skipping test step"
        fi

    - name: 🔍 Lint code
      shell: bash
      run: |
        if npm run lint --dry-run 2>/dev/null; then
          echo "🔍 Running linter..."
          npm run lint
          echo "✅ Linting completed successfully"
        else
          echo "⚠️ No linter configured, skipping lint step"
        fi

    - name: 📊 Build summary
      shell: bash
      run: |
        echo "📊 Build Summary:"
        echo "  - Node.js version: $(node --version)"
        echo "  - npm version: $(npm --version)"
        echo "  - Build output size: $(du -sh dist/ 2>/dev/null || echo 'No dist folder')"
        echo "  - Package size: $(du -sh node_modules/ 2>/dev/null || echo 'No node_modules')"
