apiVersion: v2
name: cmf-client
description: A Helm chart for CMF Client Simulator (WebSocket Test Client)
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - websocket
  - client
  - simulator
  - testing
  - frontend
home: https://github.com/yky32/cmf
sources:
  - https://github.com/yky32/cmf
maintainers:
  - name: yky32
    email: yky32@example.com
