# Production environment values for cmf-client

# Image configuration
image:
  repository: nginx
  tag: "1.25-alpine"

# Service configuration
service:
  type: ClusterIP
  port: 80

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: cmf-client.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: cmf-client-tls
      hosts:
        - cmf-client.example.com

# Replica count
replicaCount: 2

# Environment variables for client configuration
env:
  WEBSOCKET_URL: "wss://cmf.example.com"
  API_BASE_URL: "https://cmf.example.com"

# Resources (more for production)
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Pod annotations for monitoring
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "80"
  prometheus.io/path: "/metrics"
