# Development environment values for cmf-client

# Image configuration
image:
  repository: nginx
  tag: "1.25-alpine"

# Service configuration
service:
  type: ClusterIP
  port: 80

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: cmf-client-dev.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Replica count
replicaCount: 1

# Environment variables for client configuration
env:
  WEBSOCKET_URL: "ws://cmf-dev.local"
  API_BASE_URL: "http://cmf-dev.local"

# Resources (lighter for dev)
resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 25m
    memory: 32Mi
