apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cmf-client.fullname" . }}
  labels:
    {{- include "cmf-client.labels" . | nindent 4 }}
data:
  nginx.conf: |
    server {
        listen 80;
        server_name _;
        
        location / {
            root /usr/share/nginx/html;
            index client-simulator.html;
            try_files $uri $uri/ /client-simulator.html;
        }
        
        # Health check endpoint
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }
